### PR TITLE
Available xterm256

### PR DESCRIPTION
**Pull request by callmekohei**
Hello :-)

Thank you for your great program! :-)

I try to add function to use it on CUI environment.

### Environment
```bash
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

$ uname -a
Darwin callmekoheis-MacBook-Air.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

### Before

Screen Shot 2019-04-01 at 7 26 21

### After

Screen Shot 2019-04-01 at 7 26 39

### CODE REVIEW

**Comment by sh8** [comment]
Thanks for your nice PR!
In your changes, `&term` is used to check whether nvim is ran on GUI or CUI.
However, as `&term` sometimes return a weird value like `nvim` (not `xterm-256color`), I think it's better to use `has("gui_running")` instead of `&term == "xterm-256color"`.

**Comment by callmekohei** [comment]
Oh! Great!
Thank you very much!

**Comment by callmekohei** [comment]
(^_^) ping @kristijanhusak

**Comment by kristijanhusak** [comment]
@callmekohei i left a comment on a python file change. Let's just use cterm highlights by default. Check my comment.

**Comment by sh8** [comment]
@callmekohei 
As I already sent a PR to fix this problem, could you check and merge it? 
https://github.com/callmekohei/defx-icons/pull/2

**Comment by sh8** [comment]
@callmekohei
Could you check it?

**Comment by callmekohei** [comment]
Hello. Ok. I'll do it later. plaese wait a while. :-)

**Comment by kristijanhusak** [comment]
I added this. Both gui and cterm colors are applied at the same time.
To override some of them, check this section in readme. https://github.com/kristijanhusak/defx-icons#override-colors

**Comment by callmekohei** [comment]
Great thanks! 😄

**Pull request closed without merging**
